---
- name: Prepare
  hosts: all
  gather_facts: no
  tasks:
    - name: "Waiting for instance ssh connection."
      wait_for_connection:

    - name: "Set instance hostname."
      become: yes
      hostname:
        name: "{{ inventory_hostname }}"
      when: molecule_yml.driver.options.sethostname | d('yes') | bool
